# Generated by Django 3.0.7 on 2020-06-28 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statdashboard', '0003_workout_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='weight',
            field=models.FloatField(),
        ),
    ]
