# Generated by Django 3.0.7 on 2020-07-17 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('statdashboard', '0004_auto_20200628_1456'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('muscle_group', models.CharField(max_length=400)),
            ],
        ),
    ]
